[package]
name = "neusa"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-cron-scheduler = "0.9.4"
binance = { git = "https://github.com/okilimnik/binance-rs.git", rev = "10c72c6" }
teloxide = { version = "0.12", features = ["macros"] }
serde_json = "1.0.105"
serde = "1.0.183"
average = "0.14.1"
actix-web = "4.3.1"
actix-files = "0.6.2"
itertools = "0.11.0"
firestore = "0.35.1"
dotenv = "0.15.0"
lazy_static = "1.4.0"
