FROM rust:1-buster

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        cmake \
        build-essential \
        openssl \
        gcc \
        g++ \
        curl \
        git \
        libomp-dev && \

    # lightgbm
    git clone --recursive --branch stable --depth 1 https://github.com/Microsoft/LightGBM && \
    cd ./LightGBM && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make -j4 && \
    make install && \
    cd "${HOME}" && \
    rm -rf LightGBM

# rust
WORKDIR /usr/src/neusa
COPY . .
RUN cargo install --path .
CMD neusa

# docker build -f Dockerfile.trade -t neusa-trade .
# docker tag neusa-trade asia-northeast1-docker.pkg.dev/neusa-a919b/neusa/neusa-trade:latest
# docker push asia-northeast1-docker.pkg.dev/neusa-a919b/neusa/neusa-trade