import { GridBox, Button } from "std-widgets.slint";
import { Theme } from "theme.slint";

struct Price {
    price: string,
    quantity: string,
}
export component AppWindow inherits Window {
    in property <[Price]> ask;
    in property <[Price]> bid;
    in property <string> label;

    title: "Order Book Demo";
    min-width: 320px;
    min-height: 240px;
    background: Theme.palette.dark-deep-blue;
    preferred-width: 800px;
    preferred-height: 480px;

    VerticalLayout {
        Text { text: label; }
        HorizontalLayout {
            VerticalLayout {
                Text { text: "Bids"; }
                for data in root.bid: HorizontalLayout {
                    Text { text: data.price; }
                    Text { text: data.quantity; }
                }
            }
            VerticalLayout {
                Text { text: "Asks"; }
                for data in root.ask: HorizontalLayout {
                    Text { text: data.price; }
                    Text { text: data.quantity; }
                }
            }
        }
    }
}